# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
name: $(major).$(minor).$(patch)

trigger:
- master

pool: 
  name: RaspberryPi
  vmImage: 'Ubuntu-20.04'

variables:
  buildConfiguration: 'Release'
  imageApiName: 'rado94/simple-api'
  imageApiName: 'rado94/simple-api-ui'

stages:
- stage: MASTER_PIPELINE
  jobs:
  - job:
    steps:
    - task: SonarCloudPrepare@1
      displayName: SonarCloudPrepare
      inputs:
        SonarCloud: 'Sonar Cloud'
        organization: 'radoslawtaborski-github'
        scannerMode: 'MSBuild'
        projectKey: 'RadoslawTaborski_SimpleAPISolution'
        projectName: 'SimpleAPI'
        extraProperties: |
          sonar.coverageReportPaths=$(Build.SourcesDirectory)/coverlet/reports/SonarQube.xml
          sonar.coverage.exclusions=**/Migrations/*.cs,**/Models/*.cs,**/*Tests*/**/*,**/Program.cs,**/Startup.cs
    - task: DotNetCoreCLI@2  
      displayName: 'DotnetRestore'  
      inputs:  
        command: restore  
        projects: |
          **/*/*.csproj
        includeNuGetOrg: true  
    - task: DotNetCoreCLI@2
      displayName: 'DotnetBuild$(buildConfiguration)'
      inputs:
        command: 'build'
        projects: |
          **/*/*.csproj
        arguments: '--configuration $(buildConfiguration)'
    - task: UseDotNet@2
      inputs:
        version: '6.0.x'
        packageType: runtime
    - task: DotNetCoreCLI@2
      displayName: 'DotnetTest$(buildConfiguration)'
      inputs:
        command: test
        projects: '**/*Test/*.csproj'
        publishTestResults: true
        arguments: '--configuration $(buildConfiguration) --settings coverlet.runsettings.xml'
    - task: reportgenerator@5
      inputs:
        reports: '$(Agent.TempDirectory)/**/coverage.opencover.xml'
        targetdir: '$(Build.SourcesDirectory)/coverlet/reports'
        reporttypes: 'Cobertura;SonarQube'
      displayName: 'CodeCoverageReportCreation'  
    - task: PublishCodeCoverageResults@1
      displayName: 'CodeCoveragePublish'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'
    - task: SonarCloudAnalyze@1
      displayName: SonarCloudAnalyze
    - task: SonarCloudPublish@1
      displayName: SonarCloudPublish
      inputs:
        pollingTimeoutSec: '300'

- stage: MASTER_UI_PIPELINE
  jobs:
  - job:
    steps:  
    - task: NodeTool@0  
      inputs:  
        versionSpec: '16.x'  
      displayName: 'Install Node.js 16.x'  
    - task: Npm@1  
      displayName: 'AngularCLI'  
      inputs:  
        command: custom  
        verbose: false  
        customCommand: 'install @angular/cli@13.2.1'  
    - task: Npm@1  
      displayName: 'npm install'  
      inputs:  
        verbose: false   
    - task: Npm@1  
      displayName: Build  
      inputs:  
        command: custom  
        verbose: false  
        customCommand: 'run build'

- stage: MASTER_DOCKER
  jobs:  
  - job: 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageApiName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
         $(Build.BuildNumber)
         latest

- stage: MASTER_UI_DOCKER
  jobs:  
  - job: 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageUiName)'
        command: 'buildAndPush'
        Dockerfile: '**/web/simple-api-ui/Dockerfile'
        tags: |
         $(Build.BuildNumber)
         latest

- stage: MASTER_PUBLISH
  condition: succeeded()
  jobs:
  - job:
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'DotnetPublish$(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'src/SimpleAPI/SimpleAPI.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: CopyPublishBuildArtifacts@1  
      displayName: 'Copy Publish Artifact: test'  
      inputs:  
        CopyRoot: dist  
        Contents: '**'  
        ArtifactName: test  
        ArtifactType: Container 
    - task: CopyFiles@2
      displayName: 'CopyDockerCompose'
      inputs:
        contents: '**/docker-compose.yml' 
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: GithubRelease@1 
      displayName: 'CreateGitHubRelease'
      inputs:
        gitHubConnection: github.com_RadoslawTaborski
        repositoryName: 'RadoslawTaborski/SimpleAPISolution'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: $(Build.BuildNumber)
        title: $(Build.BuildNumber)
        assets: |
          $(Build.ArtifactStagingDirectory)/*.zip
          $(Build.ArtifactStagingDirectory)/docker-compose.yml
        addChangeLog: true
    - task: PublishBuildArtifacts@1
      condition: succeeded()
      displayName: 'ArtifactsPublish'

- stage: MASTER_UPDATE_VERSION
  jobs:
  - job:
    steps:
    - bash: |
        output=$(($(patch) + 1))
        echo "##vso[task.setvariable variable=newPatch;]$output"
      displayName: CalculateNewPatch
    - task: ManageVariableGroupTask@0
      displayName: UpdatePatch
      inputs:
        pat: $(pat)
        project: 'bd1ea8a2-0fd2-48a9-9eb2-8821e1b654b2'
        vgname: 'semver'
        orgname: 'radoslawtaborski'
        op: 'Update'
        varops: |
          = patch => $(newPatch)
          = patchbeta => "0"