version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    image: rado94/simple-api:${API-TAG}
    ports:
      - 5110:80
    depends_on:
      - db
volumes:
  db:
    driver: local